---
version: "3"

env:
  APPLICATION_NAME: gloner
  DEBUG: false

tasks:
  default:
    - go mod tidy

  install:
    cmds:
      - cp ${APPLICATION_NAME} /usr/local/bin/${APPLICATION_NAME}

  build:
    cmds:
      - go mod tidy
      - go env -w CGO_ENABLED=0
      - go build -ldflags '-s -w' -o ./${APPLICATION_NAME}

  lint:
    desc: run linter
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0
      - golangci-lint run .

  fmt:
    desc: run formatter
    cmds:
      - go fmt .

  upgrade-deps:
    desc: upgrade all dependencies
    cmds:
      - go get -u ./...

  vet:
    desc: run go vet
    cmds:
      - go vet

  vuln:
    desc: check for vulnerabilities
    cmds:
      - govulncheck .
